import { Product } from "@/lib/validation/schemas";

export const mockProducts: Product[] = [
  {
    id: "prod_1",
    name: "Fresh Organic Tomatoes",
    slug: "fresh-tomatoes",
    description: "Farm fresh organic tomatoes on the vine, locally sourced and packed with flavor.",
    categoryId: "cat_veg",
    vendorId: "vendor_1",
    images: ["/images/tomatoes.jpg"],
    price: 1350,
    compareAtPrice: 1500,
    unit: "1kg",
    stockQuantity: 50,
    lowStockThreshold: 10,
    isAvailable: true,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod_2",
    name: "Premium Bananas",
    slug: "fresh-bananas",
    description: "Sweet, perfectly ripe yellow bananas. Great for snacking or smoothies.",
    categoryId: "cat_fruit",
    vendorId: "vendor_2",
    images: ["/images/bananas.jpg"],
    price: 1200,
    compareAtPrice: 1400,
    unit: "1 Bunch",
    stockQuantity: 40,
    lowStockThreshold: 5,
    isAvailable: true,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod_3",
    name: "Artisan Sourdough Bread",
    slug: "artisan-sourdough",
    description: "Freshly baked artisan sourdough bread with a crispy crust and soft center.",
    categoryId: "cat_bakery",
    vendorId: "vendor_1",
    images: ["/images/bread.jpg"],
    price: 1750,
    compareAtPrice: 1900,
    unit: "1 Loaf",
    stockQuantity: 100,
    lowStockThreshold: 20,
    isAvailable: true,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod_4",
    name: "Fresh Atlantic Salmon",
    slug: "fresh-salmon",
    description: "Premium fresh pink salmon fillet, perfect for grilling or baking.",
    categoryId: "cat_meat",
    vendorId: "vendor_3",
    images: ["/images/salmon.jpg"],
    price: 3800,
    unit: "500g",
    stockQuantity: 15,
    lowStockThreshold: 5,
    isAvailable: true,
    isFeatured: true,
    isActive: true,
  }
];
