"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useCartStore } from "@/hooks/use-cart";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Lock } from "lucide-react";
import { toast } from "sonner"; // Assuming sonner is available or will be added

export default function CheckoutPage() {
  const router = useRouter();
  const { items, getCartTotal, clearCart } = useCartStore();
  const [loading, setLoading] = useState(false);

  // Form State
  const [formData, setFormData] = useState({
    fullName: "",
    phone: "",
    email: "",
    address: "",
    state: "",
    lga: "",
    instructions: ""
  });

  const subtotal = getCartTotal();
  const deliveryFee = 1000; // Can be dynamic based on state/LGA
  const total = subtotal + deliveryFee;

  if (items.length === 0) {
    return (
      <div className="container mx-auto px-4 py-16 text-center">
        <h1 className="text-2xl font-bold mb-4">Your cart is empty</h1>
        <Button onClick={() => router.push("/shop")}>Continue Shopping</Button>
      </div>
    );
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setFormData(prev => ({ ...prev, [e.target.id]: e.target.value }));
  };

  const handlePayment = async (orderId: string, orderNumber: string) => {
    try {
      const PaystackPop = (await import('@paystack/inline-js')).default;
      const paystack = new PaystackPop();
    
      paystack.newTransaction({
        key: process.env.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY || 'pk_test_placeholder',
        email: formData.email || "guest@foodxpress.com",
        amount: total * 100, // Paystack expects Kobo
        currency: "NGN",
        metadata: {
          orderId,
          custom_fields: [
            {
              display_name: "Customer Name",
              variable_name: "customer_name",
              value: formData.fullName
            },
            {
              display_name: "Phone Number",
              variable_name: "phone",
              value: formData.phone
            }
          ]
        },
        onSuccess: (transaction: any) => {
          // Webhook handles the actual verification
          clearCart();
          router.push(`/order-confirmation?id=${orderNumber}`);
        },
        onCancel: () => {
          setLoading(false);
          alert("Payment was cancelled.");
        }
      });
    } catch (error) {
      console.error("Failed to load Paystack", error);
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      // 1. Create order in backend
      const orderPayload = {
        orderNumber: "", // generated by backend
        customerInfo: {
          fullName: formData.fullName,
          phone: formData.phone,
          email: formData.email,
        },
        deliveryAddress: {
          state: formData.state,
          lga: formData.lga,
          area: formData.lga, // simplified
          street: formData.address,
          instructions: formData.instructions,
        },
        items: items.map(item => ({
          productId: item.id,
          name: item.name,
          price: item.price,
          quantity: item.cartQuantity,
          unit: item.unit,
          vendorId: item.vendorId,
          image: item.images[0]
        })),
        subtotal,
        deliveryFee,
        discount: 0,
        total,
        paymentMethod: "paystack",
      };

      const res = await fetch("/api/orders", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(orderPayload)
      });

      const data = await res.json();

      if (!res.ok) throw new Error(data.error || "Failed to create order");

      // 2. Initialize Paystack
      handlePayment(data.orderId, data.orderNumber);

    } catch (error: any) {
      console.error(error);
      alert("Error: " + error.message);
      setLoading(false);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8">Checkout</h1>
      
      <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Delivery Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="fullName">Full Name</Label>
                  <Input id="fullName" value={formData.fullName} onChange={handleInputChange} required placeholder="John Doe" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="phone">Phone Number</Label>
                  <Input id="phone" value={formData.phone} onChange={handleInputChange} required placeholder="08012345678" />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email Address</Label>
                <Input id="email" type="email" value={formData.email} onChange={handleInputChange} required placeholder="john@example.com" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="address">Delivery Address</Label>
                <Input id="address" value={formData.address} onChange={handleInputChange} required placeholder="123 Example Street" />
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="state">State</Label>
                  <select id="state" value={formData.state} onChange={handleInputChange} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2" required>
                    <option value="">Select State</option>
                    <option value="Plateau">Plateau State</option>
                    <option value="Lagos">Lagos State</option>
                    <option value="Abuja">FCT Abuja</option>
                  </select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="lga">LGA / Area</Label>
                  <Input id="lga" value={formData.lga} onChange={handleInputChange} required placeholder="Jos North" />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="instructions">Delivery Instructions (Optional)</Label>
                <Input id="instructions" value={formData.instructions} onChange={handleInputChange} placeholder="Leave at the door..." />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Payment Method</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="p-4 border rounded-lg bg-secondary/20 flex items-center gap-4 border-primary">
                <div className="flex-1">
                  <h4 className="font-semibold text-primary">Paystack</h4>
                  <p className="text-sm text-muted-foreground">Card, Bank Transfer, USSD</p>
                </div>
                <Lock className="h-6 w-6 text-primary" />
              </div>
            </CardContent>
          </Card>
        </div>

        <div>
          <Card className="sticky top-24">
            <CardHeader>
              <CardTitle>Order Summary</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-4">
                {items.map(item => (
                  <div key={item.id} className="flex justify-between items-center text-sm">
                    <div className="flex items-center gap-2">
                      <div className="font-medium">{item.cartQuantity}x</div>
                      <div className="truncate w-32">{item.name}</div>
                    </div>
                    <div className="font-semibold">₦{(item.price * item.cartQuantity).toLocaleString()}</div>
                  </div>
                ))}
              </div>
              
              <div className="border-t pt-4 space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Subtotal</span>
                  <span>₦{subtotal.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Delivery Fee</span>
                  <span>₦{deliveryFee.toLocaleString()}</span>
                </div>
                <div className="flex justify-between font-bold text-lg pt-2 border-t">
                  <span>Total</span>
                  <span className="text-primary">₦{total.toLocaleString()}</span>
                </div>
              </div>

              <Button type="submit" size="lg" className="w-full h-14 text-lg rounded-full" disabled={loading}>
                {loading ? "Processing..." : "Place Order & Pay"}
              </Button>
              <p className="text-xs text-center text-muted-foreground flex items-center justify-center gap-1">
                <Lock className="h-3 w-3" /> Secure and encrypted checkout
              </p>
            </CardContent>
          </Card>
        </div>
      </form>
    </div>
  );
}
